version: "3.9"
services:
  mypg:
    image: postgres:15.3
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    restart: unless-stopped
    environment:
      POSTGRES_USER: mdishmamiqbal
      POSTGRES_PASSWORD: password
      POSTGRES_DB: teebay
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    networks:
      - default

  web:
    build: ./frontend
    ports:
      - 5173:5173

  prisma-postgres-api:
    build: ./backend
    container_name: prisma-postgres-api
    env_file:
      - ./backend/.env
    depends_on:
      - mypg
    ports:
      - "3001:3001"
    restart: always
    networks:
      - default

volumes:
  postgres:
