version: "3.8"
services:
  web:
    build: ./frontend
    ports:
      - 3000:5173
  api:
    build: ./backend
    ports:
      - 3001:3001
    env_file:
      - ./backend/.env
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: mdishmamiqbal
      POSTGRES_PASSWORD: password
      POSTGRES_DB: teebay_db
    ports:
      - "5432:5432"
